---
title: "Figure 2. Classification and prediction of the likelihood of SARS-CoV-2 host species and identification of enriched k-mers after the comparison of isolates between deer and bats."
author: "Janusz Wiśniewski and Heng-Chang Chen"
date: "2025/03/25"
output: multiple formats of the results
---

Please note, the code wriiten for the construction of the classifier and corresponding plots can be referred to as deer_classifier.ipynb and bat_classifier.ipynb archived in [GitHub PORT-EK notebooks](https://github.com/wis-janusz/PORT-EK/tree/main/notebooks).

The code for the calculation of enriched k-mers and analytical pipelines, including plotting related to Figure 2B, 2C, 2D, and 2E can be referred to as bat_vs_deer_analysis.ipynb and bat_vs_deer_classifier.ipynb archived in [GitHub PORT-EK notebooks](https://github.com/wis-janusz/PORT-EK/tree/main/notebooks).

The code for the phylogenetic trees (Figures 2F and 2G) can be referred to as bat_vs_deer_phylo.ipynb archived in [GitHub PORT-EK notebooks](https://github.com/wis-janusz/PORT-EK/tree/main/notebooks). The input files (Fig_2F_bat_deer_phylo_tree.xml and Fig_2G_bat_deer_kmer_tree.xml) for the visualization of the phylogenetic trees (Figures 2F and 2G) are provided in this folder (Fig_2).
